### ISSUE TITLE
How to add more event. 

### ISSUE THREAD

**Issue by TeerasakGame** [jshor/datebook#100]

**Comment by jshor** [comment]
The online calendar services limit to only one event at a time, and multiple iCalendar downloads will be blocked by some browsers.

However, you can add multiple events by calling the library multiple times for each event:

```js
const events = [
  {
    title: 'My event 1',
    start: '2020-07-04T19:00:00',
    end: '2020-07-04T23:30:00'
  },
  {
    title: 'My event 2',
    start: '2020-07-04T19:00:00',
    end: '2020-07-04T23:30:00'
  }
]

const googleCalendarUrls = events.map(e => (new GoogleCalendar(e)).render())
```

**Comment by jshor** [comment]
In [V6 (PR #126)](https://github.com/jshor/datebook/pull/126), which will be released this week., you will be able to do the following to add multiple events to a single `.ics` file:

```ts
const secondEvent = new ICalendar({
  title: 'Monthly Meeting with Boss Man',
  location: 'Conference Room 2A, Big Company, Brooklyn, NY',
  description: 'Meeting to discuss weekly things'
  start: new Date('2022-07-08T19:00:00'),
  recurrence: {
    frequency: 'MONTHLY'
  }
})

icalendar.addEvent(secondEvent)
```

Note that this feature can't be implemented for other services (such as Yahoo! Calendar) as multiple events for them via query string are not supported.
