### ISSUE TITLE
Add Timezon

### ISSUE THREAD

**Issue by Mohitpokra** [jshor/datebook#104]
is there any way by which We can set timezone in google calendar ?

**Comment by jshor** [comment]
As of v4.1.8, you'll now be able to pass the `start` and `end` params as `Date` objects instead of strings, which gives you full control over the date and timezone

Example:

```js
const icalendar = new ICalendar({
  title: 'Happy Hour',
  location: 'The Bar, New York, NY',
  description: 'Let\'s blow off some steam with a tall cold one!',
  start: new Date('2022-07-08T19:00:00+05:00'),
  end: new Date('2022-07-08T23:30:00+05:00'),
  recurrence: {
    frequency: 'WEEKLY',
    interval: 2
  }
})
```

Note that passing dates as strings is still supported for backward compatibility, but will be removed in v5.0.0.

**Comment by jshor** [comment]
Just a heads up: **v4.1.9** will correct date/time to enforce UTC -- in other words, the timezone that the user is in will be the timezone that is used in the calendars.
