### ISSUE TITLE
Reduce bundle size?

### ISSUE THREAD

**Issue by rayshan** [jshor/datebook#105]
Thanks for building datebook! I was really looking forward to using it until I saw the [bundle size](https://bundlephobia.com/result?p=datebook@4.1.5). 30 kb minified + gzipped is almost as big as React. Any thoughts on reducing the bundle size?

~What do you think about removing moment and let users format their own dates? Here's a related library that uses this approach: https://github.com/jasonleibowitz/react-add-to-calendar-hoc~ nevermind I see that moment is only used for tests.

**Comment by jshor** [comment]
Sorry for this oversight. Looks like the `mode` was set to `development`, which caused the source map to be part of the bundle. This will be fixed in the next minor release.

The bundle size should be reduced from `108KB` to `16KB`.
