### ISSUE TITLE
Need for Content Security Policy directive 'unsafe-eval' blocks datebook usage in some environments

### ISSUE THREAD

**Issue by rayshan** [jshor/datebook#106]
I'm using datebook in a Chrome Extension with this CSR directive:

`"script-src 'self' https://www.google-analytics.com; object-src 'self'"`

Importing the bundled library results in this error:

`import {GoogleCalendar} from "datebook";`

`Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' https://www.google-analytics.com".`

Importing the unbundled library works fine:

`import GoogleCalendar from "datebook/src/GoogleCalendar";`

Is it possible to remove the need to do `unsafe-eval`? Searching for `eval` doesn't lead to what datebook is eval'ing.

**Comment by jshor** [comment]
@rayshan thanks for reporting this issue. Would you be able to produce a quick test repo that replicates this issue?

**Comment by rayshan** [comment]
Fixed by 4.1.6
