### ISSUE TITLE
All-day events are set to the wrong date due to time zone difference

### ISSUE THREAD

**Issue by rayshan** [jshor/datebook#107]
To reproduce: in the PST time zone, pass `2020-09-24` as the `start` option. `GoogleCalendar` produces a calendar invite for 2020-09-23.

Looks like this library is parsing user's string input [here](https://github.com/jshor/datebook/blob/master/src/CalendarBase.js#L67). `new Date("2020-09-24")` in the PST time zone is parsed as `Wed Sep 23 2020 17:00:00 GMT-0700 (Pacific Daylight Time)`. Maybe delegate the responsibility of properly format the datetime string to the library consumer?

**Comment by jshor** [comment]
It appears that when the date is parsed as a string, the timezone won't be parsed if it's not passed in.

As of v4.1.8, you can now pass the `start` and `end` params as `Date` objects instead of strings, which gives the consumer full control over the date and timezone.

**Comment by jshor** [comment]
Just a heads up: **v4.1.9** will correct date/time to enforce UTC -- in other words, the timezone that the user is in will be the timezone that is used in the calendars.
