### ISSUE TITLE
.ics files not downloding on mobile safari

### ISSUE THREAD

**Issue by davidmyers-a** [jshor/datebook#119]
Looks like the change made in https://github.com/jshor/datebook/issues/94 to detect safari and not edge works for safari on the mac desktop but doesn't work for safari on iOS (iPhone, iPad).

`window.hasOwnProperty('safari')`

Could use something like below:
`/^((?!chrome|android).)*safari/i.test(navigator.userAgent)`
Stolen (borrowed) from: https://stackoverflow.com/questions/7944460/detect-safari-browser

**Comment by jshor** [comment]
Gah, what a mess browser userAgents have become!

@davidmyers-a I don't have an iOS device. Could you please try [this test](https://jsfiddle.net/b65r1qLc/) on various iOS browsers and confirm that it tells you it's detecting iOS Safari properly?

**Comment by davidmyers-a** [comment]
They indeed are frustrating, maybe UA client hints will be better (I'm not holding my breath for that though).

Ok tested the js fiddle and it worked for:
- iPhone Safari on iOS
- iPhone Chrome on iOS (probably not good that this matches as  can't open the ics file afterwards)
- iPad Safari on iOS
- MacBook Pro Safari MacOs

So the above scripts solves for safari on all platforms that i had access to. I also tried the code in the datebook library and i could download/open the ics file again, except for chrome on iOS.

For Chrome on iOS it appears to be very limited. You can use webcal://your_link.ics to allow some form of functionality but its subscribing to the event as a calendar (apparently this is what addevent does). Otherwise it just downloads the file but you can't open it up in the calendar.
https://stackoverflow.com/questions/15972628/ics-file-download-fails-on-iphone-chrome-with-unknown-file-type
You can determine the chrome on iOS by using searching for CriOS (e.g. Cr-ome-iOS).
if(navigator.userAgent.match('CriOS'))
https://developer.chrome.com/multidevice/user-agent

**Comment by jshor** [comment]
@davidmyers-a Here is a test using the iOS fixes: https://jshor.github.io/safari-test/dist/

Can you verify that the ICS downloads properly on iOS browsers?

So far, it seems to work in the following browsers:

* Windows Chrome
* Windows Firefox
* Android Chrome
* MacOS Safari
* MacOS Chrome

Did not work:
* Android Firefox Focus (see #125)
