### ISSUE TITLE
4.1.5 used to accept undefined for `start` and `end` date

### ISSUE THREAD

**Issue by albertpeiro** [jshor/datebook#127]
Hi there,

4.1.5 used to accept undefined for `start` and `end` date.
At some point along 4.1.x this broke and caused a bug in our app (we used ^). We rely on the ability to send undefined for these heavily as a feature of our product. Our app had automatically package-locked this on 4.1.11 , so this version for sure breaks.

Just sharing in case anyone experiencing the same.

I've tried 5 and it doesn't seem to support it, although the spec for all ical type of urls and files does seem to support it - and in our testing it works too including .ics files.

It'd be nice if 5 supported it in the future.

**Comment by jshor** [comment]
Sorry to hear that this For `end` dates, if they're omitted from the options, they default to 24 hours after the `start` date. The `start` param was never intended to be optional.

May I ask what the use case for passing in `start` as `undefined` is? I would think every event would need to start at some point, but maybe I can release an update to this behavior if I knew what the use case is.

**Comment by albertpeiro** [comment]
Hey @jshor thanks a ton for your library and all the cool work you're doing with it 🥇 

We're passing `undefined`, but what we really mean to express is: "there's no date" and "the date can be chosen by the receiver"
In practice what this means is that the recipient of the event gets to choose what time they want to have the event at.
Calendar providers actually let them choose and also give them a default time - it normally is just "now".
Basically our intent is to drive people into a shop, no matter what time they come, it is useful for them to choose what time they want to have the event at, instead of trying to program a time upfront, which is unfeasible in our use case.

<img width="352" alt="Screenshot 2020-10-22 at 15 26 12" src="https://user-images.githubusercontent.com/1984397/96885878-eece5f80-147a-11eb-8184-b19de2ff4ccf.png">
<img width="1330" alt="Screenshot 2020-10-22 at 15 29 33" src="https://user-images.githubusercontent.com/1984397/96886438-7ddb7780-147b-11eb-9174-4708b08364c3.png">

Passing undefined, or simply not passing the keys would both work for us, we'd be happy with either. But personally if the library is to support it I think it should be easy to support both.

Let me know what you think and if you need more detail on the use case and thanks a ton for looking into this 💯

**Comment by jshor** [comment]
@albertpeiro Got it. I did some investigation into this. Unfortunately while this would work for Google Calendar and Outlook Web (both default to the current user time), it won't work for Yahoo or ICS:

1. For ICS files, the [`DTSTART`](https://www.kanzaki.com/docs/ical/dtstart.html) property is required. ICS files don't have the ability to fall back to the current user time.

2. For Yahoo! Calendar, both the `st` (start time), and either `et` (end time) or `dur` (duration) are required for the URL to work. So for the moment, if you're not passing in the `start` for Yahoo Calendar in your app, the URL is probably broken.

One alternative for you guys may be to pass `start` as `new Date()` when generating the URL. Although I could build this approach in Datebook, I'm concerned about making the common config object result in inconsistent behavior across calendars.

**Comment by albertpeiro** [comment]
@jshor thanks for looking into this. We do have our own code to do what this lib does (but not as elegantly) in a different part of the platform and it seemed to work. I'll double check with the testing people. Also the whole thing without dates cleared testing 3 months ago, so I'll double check with them if they did in fact test the final result with Yahoo but I'd expect they did.

Passing `new Date()` is not ideal as it will mean that the date will always be set to the past for the user when they open the invite.

**Comment by jshor** [comment]
@albertpeiro I just made a test with 4.1.5, but I see that when `start` is set to `undefined`, the date in the query string param becomes `NaNaNaN/NaNaNaN` (that was reported in #84, and the fix for that is probably what broke things on your guys' end).

Basically I'm not sure how the library ever could've worked with passing `start` as `undefined`

Here's the test code I used for this:

```js
import {
  ICalendar,
  YahooCalendar,
  GoogleCalendar,
  OutlookCalendar
} from 'datebook'

const config = {
  title: 'Happy Hour',
  location: 'The Bar, New York, NY',
  description: 'Let\'s blow off some steam with a tall cold one!',
  start: ''
}

console.log('ICS: ', (new ICalendar(config)).render())
console.log('Yahoo: ', (new YahooCalendar(config)).render())
console.log('GoogleCalendar: ', (new GoogleCalendar(config)).render())
console.log('OutlookCalendar: ', (new OutlookCalendar(config)).render())
```

**Comment by jshor** [comment]
@albertpeiro in 6.1.0, you can now remove query string parameters from URLs using [YahooCalendar.setParam()](https://datebook.dev/docs/yahoo.html#setparam-key-string-value-string-yahoocalendar), [GoogleCalendar.setParam()](https://datebook.dev/docs/google.html#setparam-key-string-value-string-googlecalendar), or [OutlookCalendar.setParam()](https://datebook.dev/docs/outlook.html#setparam-key-string-value-string-outlookcalendar) by passing in a value of `null`.

For your use case, you can do the following to remove the date/times:

```ts
const config = {
  title: 'Happy Hour',
  location: 'The Bar, New York, NY',
  description: 'Let\'s blow off some steam with a tall cold one!',
  start: new Date()
}

const yahoo = new YahooCalendar(config)
const google = new GoogleCalendar(config)
const outlook = new OutlookCalendar(config)

yahoo
  .setParam('st', null)
  .setParam('et', null)
google 
  .setParam('dates', null)
outlook 
  .setParam('startdt', null)
  .setParam('enddt', null)
```

I do want to reiterate that doing this for Google and Outlook will just make the event default to the current time when opened by the user, and will make Yahoo calendar break entirely.

Hopefully this provides more flexibility with mutating the URLs however.
