### ISSUE TITLE
add attendees?

### ISSUE THREAD

**Issue by mihristov** [jshor/datebook#131]
Hi. I need to add attendees to the event. Does that library support it?

**Comment by jshor** [comment]
For now, Datebook doesn't have an elegant way of adding attendees (though this will change in a future version). However, here's how you'd accomplish it using the library:

# iCalendar

For iCalendar, you'll need to use [`addProperty()`](https://datebook.dev/docs/icalendar.html#addproperty-key-string-value-icspropertyvalue) with the `key` set to `ATTENDEE`, with any desired options appended:

Example:

```ts
const icalendar = (new ICalendar(options))
  .addProperty('ATTENDEE;ROLE=REQ-PARTICIPANT;CN=John Doe', 'MAILTO:johndoe@example.com')
  .addProperty('ATTENDEE;ROLE=OPT-PARTICIPANT;CN=Jane Doe', 'MAILTO:janedoe@example.com')
  .render()
```

## Optional Parameters:

* [**`DELEGATED-FROM`**](https://www.kanzaki.com/docs/ical/delegatedFrom.html) - Delegatee of the request
* [**`PARTSTAT`**](https://www.kanzaki.com/docs/ical/partstat.html) - Participation status
* [**`ROLE`**](https://www.kanzaki.com/docs/ical/role.html) - Required, optional, etc.
* [**`RSVP`**](https://www.kanzaki.com/docs/ical/rsvp.html) - Whether or not to RSVP automatically (`TRUE` or `FALSE`)
* [**`SENT-BY`**](https://www.kanzaki.com/docs/ical/sentBy.html) - Event sender

# Outlook Web Calendar

For OWA, you'll need to add the **`to`** query string param (for required attendees) and **`cc`** (for optional attendees), using comma-separated list of guests as the values. 

Example:

```ts
let outlookWeb = (new OutlookCalendar(options)).render()

outlookWeb += `&to=John Doe <johndoe@example.com>,Jane Doe <janedoe@example.com>&cc=Billy Joel <bjoel@music.com>`
```


# Google Calendar

For Google Calendar, you'll need to add the **`add`** query string param, with a comma-separated list of guests as the value. Note: the differentiation between *optional* and *required* is not supported.

Example:

```ts
let googleCalendar = (new GoogleCalendar(options)).render()

googleCalendar += `&to=John Doe <johndoe@example.com>,Jane Doe <janedoe@example.com>`
```

# Yahoo Calendar

Does not support attendees via web links.

**Comment by csakai** [comment]
Josh and I spoke about this earlier. I will take a crack at it. Should be able to submit a PR today or tomorrow.

**Comment by rvmladenov** [comment]
If I add 2 people for ics - I am still missing the second person

**Comment by jshor** [comment]
@rvmladenov what does your code look like? [This fiddle](https://jsfiddle.net/ead86kf9/) shows the two attendees added when rendered:

```js
const { ICalendar } = window.datebook

const ics = new ICalendar({
  title: 'Happy Hour',
  location: 'The Bar, New York, NY',
  description: 'Let\'s blow off some steam with a tall cold one!',
  start: new Date('2022-07-08T19:00:00'),
  end: new Date('2022-07-08T23:30:00'),
  // an event that recurs every two weeks:
  recurrence: {
    frequency: 'WEEKLY',
    interval: 2
  }
})
  .addProperty('ATTENDEE;ROLE=REQ-PARTICIPANT;CN=John Doe', 'MAILTO:johndoe@example.com')
  .addProperty('ATTENDEE;ROLE=OPT-PARTICIPANT;CN=Jane Doe', 'MAILTO:janedoe@example.com')
  .render()

console.log('ICS data: ', ics)
```

Output

```
BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VEVENT
CLASS:PUBLIC
DESCRIPTION:Let's blow off some steam with a tall cold one!
DTSTART:20220708T230000Z
DTEND:20220709T033000Z
LOCATION:The Bar, New York, NY
SUMMARY:Happy Hour
TRANSP:TRANSPARENT
RRULE:FREQ=WEEKLY;INTERVAL=2
ATTENDEE;ROLE=REQ-PARTICIPANT;CN=John Doe:MAILTO:johndoe@example.com
ATTENDEE;ROLE=OPT-PARTICIPANT;CN=Jane Doe:MAILTO:janedoe@example.com
END:VEVENT
END:VCALENDAR
UID:3v73hqcfdnh
DTSTAMP:20201204
PRODID:fiddle.jshell.net
```

**Comment by csakai** [comment]
Just wanted to give a little update, I know I said I'd have something in on Thursday or Friday. Life, ya know? Anyway, I'm currently implementing attendees for each calendar type. The query string types are pretty trivial, but the ICal type is a little tricky. On first blush, it looks like it may need a refactor, but it might not be necessary. It's doable, I may submit the full functionality for ICal separately.
