### ISSUE TITLE
Angular usage

### ISSUE THREAD

**Issue by adamalexandru4** [jshor/datebook#142]
I'm trying to use datebook but i can't figure it out how to do it in Angular.
I get the error that the library isn't compiled correctly and i should add it to files or include in tsconfig.app.json.

Any solution ?

**Comment by jshor** [comment]
@adamalexandru4 there was an issue where the build was not including the `*.ts` files in the `dist/` folder. It's been fixed as of v6.3.1 and will probably fix your issue.
