### ISSUE TITLE
provide your own uid

### ISSUE THREAD

**Issue by AlexDhaenens** [jshor/datebook#143]
Instead of creating a random uid for the ical file ("UID" property), a developer can provide his/her own.

**Comment by jshor** [comment]
@AlexDhaenens I've introduced a method `setMeta()` on `ICalendar` which will allow you to override the `UID` like so:

```ts
const icalendar = (new ICalendar(props))
  .setMeta('UID', 'my-custom-uid')
```

More info on that method [here](https://datebook.dev/docs/icalendar.html#setmeta-key-string-value-string).

Yahoo! Calendar also supports custom UIDs, and one can be added using the `setParam()` method like so:

```ts
const yahooCalendar = (new YahooCalendar(props))
  .setParam('uid', 'my-custom-uid')
```

More info on that method [here](https://datebook.dev/docs/yahoo.html#setparam-key-string-value-string-yahoocalendar).

**Comment by AlexDhaenens** [comment]
Ah I see, I seem to have missed that part. My apologies
