### ISSUE TITLE
Outlook Url are not longer valid

### ISSUE THREAD

**Issue by aleBurgos** [jshor/datebook#149]
The current URL` https://outlook.live.com/calendar/0/deeplink/compose` is no longer valid anymore, 
it should be `https://outlook.office.com/calendar/0/deeplink/compose`.

**Comment by jshor** [comment]
My understanding is that `live.com` is in use for personal Outlook accounts, whereas `outlook.com` is for Office365 ones.

In #150 I'm implementing `setHost`, which will allow you to specify which calendar URL you prefer (`live` for personal, or `office` for Office365).
