### ISSUE TITLE
Safari on ios shows incorrect dates

### ISSUE THREAD

**Issue by asunar** [jshor/datebook#157]
I have an ics file generated by datebook. All dates looks correct and chrome/safari on mac can successfully import the events. However, safari on ios is incorrectly showing event dates one day earlier. I verified that the timezone is correct on ios. Not necessarily a datebook issue but was wondering if anyone else ran into this.

Thanks.

**Comment by jshor** [comment]
@asunar could you provide the code that you used to generate the ICalendar? Does this issue also occur on iOS with other calendars (google/yahoo/outlook)?

**Comment by asunar** [comment]
Import works fine on mac (firefox) with default calendar, on windows(firefox) with outlook. The issue occurs on ios 14.4.2 with safari.

Note the dates in the screenshot do not match the dates in json.
```
/*
[{"eventDate":"2021-05-31","details":". Memorial Day"},{"eventDate":"2021-06-08","details":". testevent"},{"eventDate":"2021-06-09","details":"Anniver sary"},{"eventDate":"2021-06-09","details":"Client Meeting"},{"eventDate":"2021-06-09","details":"Trash day"},{"eventDate":"2021-06-11","details":"Soccer Game"},{"eventDate":"2021-06-14","details":"Lab appointment"},{"eventDate":"2021-06-15","details":"Beach"},{"eventDate":"2021-06-19","details":"Juneteenth"},{"eventDate":"2021-06-20","details":"Father's Day"}]
*/

      function generateDateWithoutTime(dateString) {
        //expected format: "2021-06-06"
        const dateParts = dateString.split('-')
        return new Date(dateParts[0], dateParts[1] - 1, dateParts[2])
      }

      function downloadIcs(events){
        const firstEvent = events.shift();
        
        const options = {
          title: firstEvent.details,
          description: firstEvent.details,
          start: generateDateWithoutTime(firstEvent.eventDate),
        }
        
        /* global datebook */
        const icalendar = new datebook.ICalendar(options)
        events.forEach(event => {
          const icsEvent = new datebook.ICalendar({
            title: event.details,
            desription: event.details,
            start: generateDateWithoutTime(event.eventDate),
          })
          
          icalendar.addEvent(icsEvent);
        }); 
        
        console.log(icalendar.render());        
        icalendar.download()
      }
```
![image](https://user-images.githubusercontent.com/204049/121389833-6968c400-c912-11eb-8d3e-5d073efeabc2.png)

**Comment by jshor** [comment]
@asunar not all `Date` constructors on all browsers are implemented the same way. I think this issue may be due to how iOS Safari parses dates.

I would try constructing a `Date` using your `generateDateWithoutTime` function and log it, and see if the date rendered is correct.

**Comment by asunar** [comment]
Date rendered looks correct.
![image](https://user-images.githubusercontent.com/204049/121423860-536cfa80-c936-11eb-9db2-539576aafc46.png)

Date in the generated ics looks correct as well.
![image](https://user-images.githubusercontent.com/204049/121424031-80b9a880-c936-11eb-9216-802c6842c7ac.png)

Date in the Add event(s) window on ios is incorrect: May 30 (see above).

**Comment by jshor** [comment]
I think in this case, the iOS app is converting the date from UTC to CDT (i.e., `2021-05-31` at midnight UTC is really `2021-05-30` at 7pm CDT), but since the event is all-day, the time difference is not apparent.

It's possible that removing the trailing `Z` from `DTSTART` and `DTEND` might fix the bug

**Comment by asunar** [comment]
Is there a config option I can use to tell datebook to remove the trailing Z?

**Comment by jshor** [comment]
There isn't. I figure just remove it manually from the generated .ics file for a quick test

**Comment by asunar** [comment]
ics npm package seems to be generating an ics that works across the board. It looks like this.
