### ISSUE TITLE
Does this have webcal support?

### ISSUE THREAD

**Issue by saheedoladele-outlier** [jshor/datebook#161]
Hi! Is there some way to add series of events to google calendar or any other calendar with a single click using `webcal` or any other protocol?

I see we can pre-fill a google calendar event, but can we do the same for multiple events? Thanks in advance.

**Comment by jshor** [comment]
Hi @saheedoladele-outlier - you can generate an ICS file using Datebook, but you'd need to host the generated ICS file on a server in order for a `webcal` link to work. An example link could be something like `webcal://example.com/sampleEvent.ics`

Here's a Node.js example on how you could create an ICS file for `webcal` links using Datebook:

```ts
import { ICalendar } from 'datebook'
import fs from 'fs'

const config: CalendarOptions = {
  title: 'Happy Hour',
  location: 'The Bar, New York, NY',
  description: 'Let\'s blow off some steam with a tall cold one!',
  start: new Date('2022-07-08T19:00:00'),
  end: new Date('2022-07-08T23:30:00'),
  attendees: [
    {
      name: 'John Doe',
      email: 'john@doe.com',
      icsOptions: {
        rsvp: true
      }
    },
    {
      name: 'Jane Doe',
      email: 'jane@doe.com'
    }
  ],
  // an event that recurs every two weeks:
  recurrence: {
    frequency: 'WEEKLY',
    interval: 2
  }
}

const icalendar = new ICalendar(config)

fs.writeFileSync('sampleEvent.ics', icalendar.render())
```

More documentation on `ICalendar` can be found [here](https://datebook.dev/docs/icalendar.html).
