### ISSUE TITLE
What are the prerequisites to use datebook?

### ISSUE THREAD

**Issue by catherineluse** [jshor/datebook#163]
I can't get the examples working because it doesn't say what the import statements are. For example, 

```
const icalendar = new ICalendar(config)
```
or
```
const googleCalendar = new GoogleCalendar(config)
```
I would need to import ICalendar and GoogleCalendar, but how and from where?

https://datebook.dev/docs/

**Comment by jshor** [comment]
Hi @catherineluse - a basic example can be found on [the homepage doc](https://datebook.dev/#example-usage), but you're right that the docs should clarify this better. I recently [updated the basic doc](https://datebook.dev/docs/#example-usage) to contain examples on how to import and [additional documentation to use it via `<script>` import](https://datebook.dev/docs/#via-script-import).
