### ISSUE TITLE
Recurring option is not working in yahoo url

### ISSUE THREAD

**Issue by scriptbeedj** [jshor/datebook#165]
Input

```
{
  "title": "Test ",
  "description": "dsds",
  "start": "2021-08-24T11:00:00.000Z",
  "end": "2021-08-24T12:30:00.000Z",
  "recurrence": {
    "frequency": "WEEKLY",
    "interval": 1,
    "weekdays": [
      "SU",
      "TU",
      "WE"
    ],
    "until": "2021-10-30T00:00:00Z"
  },
  "location": "none"
}
```

**Generated Yahoo url:**
https://calendar.yahoo.com/?v=60&title=Test%20&desc=dsds&in_loc=sds&st=20210824T040000&dur=0130&RPAT=01WkSuTuWe&REND=20210831

![image](https://user-images.githubusercontent.com/67512178/130733358-4a63e5d6-d03a-4741-85ec-591fa63cd800.png)

But same configuration working as expected for google

Google URL:
https://calendar.google.com/calendar/render?action=TEMPLATE&dates=20210824T112952Z%2F20211001T043000Z&text=Test%20&details=dsds&location=sds&allday=false&recur=RRULE%3AFREQ%3DWEEKLY%3BINTERVAL%3D1%3BBYDAY%3DSU%2CTU

**Comment by jshor** [comment]
After some investigation, it appears that Yahoo has unfortunately removed the ability to specify recurrences.

**Comment by maryamaljanabi** [comment]
Hi @jshor recurring events don't work in Outlook Online Calendar as well. Did Outlook remove the ability to add recurring events as well? Or is there a way to do it?
