### ISSUE TITLE
"Unable to launch event" opening ICS file on Android

### ISSUE THREAD

**Issue by claytongulick** [jshor/datebook#169]
When calling .download() to create an ICS file on android, the file downloads but an error "Unable to launch event" is shown when trying to open it.

Could be related to: https://stackoverflow.com/questions/35918537/android-google-calendar-unable-to-launch-event

**Comment by jshor** [comment]
@claytongulick could you provide the code you were using to render the calendar/invoke `download()`?

I could not reproduce the issue using [the calendar generator](https://datebook.dev/generators/) on Android 11 using Chrome 94.0.4606.50. It was able to open in Calendar without issue.
