### ISSUE TITLE
[Question] Is it possible to include a hyperlink within a description field?

### ISSUE THREAD

**Issue by CodyBontecou** [jshor/datebook#176]
Is there a solution to include a string with a hyperlink within my description parameter?

**Comment by Snugg-App** [comment]
Yes I've had no problems just injecting HTML within the description.

e.g.

`const options: CalendarOptions = {
            title: title,
            description: `You have a scheduled a session.
            <br/> Join session <a href="${sessionURL}">${sessionURL}</a>`,
            start: new Date(bookedSession.start),
            end: new Date(bookedSession.end)
};`

**Comment by jshor** [comment]
You can inject HTML, but whether it will render in the calendar application is dependent on whether the client will parse it.
