### ISSUE TITLE
Add support for uid and status properties

### ISSUE THREAD

**Issue by dav1dc-cam** [jshor/datebook#180]
It would be great if datebook supported the uid and status properties. It would make it possible to cancel existing events by creating an event with a given uid and then creating a subsequent event with the same uid and a status of 'cancelled'

**Comment by jshor** [comment]
You can set `UID` and `STATUS` properties by using the [`setMeta()` method of `ICalendar`](https://datebook.dev/docs/icalendar.html#setmeta-key-string-value-string). Here's an example:

```ts
const icalendar = new ICalendar(config)

icalendar
  .setMeta('UID', 'e9de89b0a5e9ad6efd5e5ab543ec617c')
  .setMeta('STATUS', 'TENTATIVE')
  .render()
```
