### ISSUE TITLE
Angular 13 + jest v27 incompatibility

### ISSUE THREAD

**Issue by gagle** [jshor/datebook#181]
Angular 13 introduced a change and now tries to load dependencies in ESM format. This lib is incompatible and is a huge major blocker for migrating to Angular 13. As a temporary workaround I'm using the path alias:

````
"datebook": ["datebook/dist/index.js"],
````

**Comment by NishaJKulal** [comment]
Any updates on this issue?

**Comment by NishaJKulal** [comment]
@gagle Could you please provide more details on the workaround mentioned? Where do we need to add the path changes?
Thanks in advance

**Comment by jshor** [comment]
Datebook v7.1.0 now exports an ESM module which should take care of the issue.
