### ISSUE TITLE
Simple html example showing which files in the distribution need to be referenced

### ISSUE THREAD

**Issue by jongund** [jshor/datebook#185]
Could you create a simple HTML file showing which files need to be included to use the import from with in a HTML file:

`import { ICalendar } from 'datebook'`

There are a lot of files in the `dist` folder to know wich ones need to be references.
Would be possible to have a single minified file to reference from a web page, maybe even using a CDN to reference the file?

**Comment by jshor** [comment]
@jongund [here](https://datebook.dev/docs/#via-script-import) is an example on how to use Datebook directly via `<script>` import:

```html
<!doctype html>
<html>
  <head>
    <script src="https://cdn.jsdelivr.net/npm/datebook"></script>
  </head>
  <body>
    <script>
      const ical = new datebook.ICalendar({
        title: 'Happy Hour',
        location: 'The Bar, New York, NY',
        description: 'Let\'s blow off some steam with a tall cold one!',
        start: new Date('2022-07-08T19:00:00'),
        end: new Date('2022-07-08T23:30:00'),
        // an event that recurs every two weeks:
        recurrence: {
          frequency: 'WEEKLY',
          interval: 2
        }
      })

      ical.download()
    </script>
  </body>
</html>
```

**Comment by jongund** [comment]
Thank you!
