### ISSUE TITLE
.ics file's RRULE doesn't contain UNTIL parameter when setting it up in config object

### ISSUE THREAD

**Issue by elzaratveego** [jshor/datebook#188]
![image](https://user-images.githubusercontent.com/95632945/155066366-422d561d-b290-4958-9695-29ab46ce0cc5.png)

**Comment by ykhan21** [comment]
Hey, @jshor. I believe the reason it's not showing in the .ics is because the "until" should be "end" in the Datebook Config Object.

Also, Is the script that generates the files on the Calendar Generators page public? If so, where can I find them?

**Comment by jshor** [comment]
hi @ykhan21, I updated the generator and now the `end` param fills in properly. The code for that [can be found here](https://github.com/jshor/datebook/blob/master/docs/.vuepress/components/forms/Recurrence.vue#L223-L225).
