### ISSUE TITLE
Description is cut off

### ISSUE THREAD

**Issue by demonspear** [jshor/datebook#58]
I saw description is cut off. Only 62 character will show in description. Please fix!

**Comment by neodcalgary** [comment]
Should be an easy fix: 

original code: 
`"DESCRIPTION:"+i.default.formatIcsText(e.description,62)`

**Comment by jshor** [comment]
The max length for `SUMMARY`, `DESCRIPTION`, and `LOCATION` have all been removed in accordance with RFC-5545.

This should now be fixed as of v4.1.1.
