### ISSUE TITLE
Support NodeJS generation

### ISSUE THREAD

**Issue by ScreamZ** [jshor/datebook#65]
Hello @jshor,

What if we need to generate ICS and Google URL for NodeJS or SSR ?

This is currently really problematic, the library is nice…

As far as i can see, It's related to your parcel bundler, which make any import to resolve to undefined.

Also for Ical you're building URL using window.host, which should be a param if possible

Thanks

**Comment by jshor** [comment]
Thanks for the suggestion @ScreamZ. SSR is now supported as of v4.1.0.

**Comment by ScreamZ** [comment]
I'll try that soon, thanks @jshor.

I'll send some mails with calendar links and ics
