### ISSUE TITLE
Bug on IE11

### ISSUE THREAD

**Issue by hzrcan** [jshor/datebook#91]
Hi,

I found a bug in Internet Explorer 11. When I use the datebook node module, my page is not loading and I get the error:

`Unhandled promise rejection Error: (SystemJS) Syntax Error`. See below:

![error-datebook](https://user-images.githubusercontent.com/3510239/84274836-a0a26a80-ab30-11ea-963e-0e5aa0daf21c.png)

If I comment out the calendar.js, the page loads but this time addToCalendar is not working. 

![error-datebook2](https://user-images.githubusercontent.com/3510239/84274722-8072ab80-ab30-11ea-9398-0518d27bb0ef.png)

Look likes there is something wrong with using a method which is not compatible with Internet Explorer 11. 

Can you check please? I think the issue is in one of the import files. I'm searching for the method which isn't compatible. I will let you know if I found something.

But maybe you can look also.

**Comment by hzrcan** [comment]
![error-datebook3](https://user-images.githubusercontent.com/3510239/84356267-3dfaae80-abc4-11ea-8ee4-63198d2548aa.png)


is going wrong when you use polyfills.

**Comment by jshor** [comment]
Thanks for catching the issue @hzrcan. I just tested in IE11, and should be good to go now.

Datebook v4.1.3

**Comment by hzrcan** [comment]
The version 4.1.3 is not released and when I change it locally I still get the same error.

**Comment by hzrcan** [comment]
@jshor  Tried the 4.1.3 version. The issue is still there in IE11, in combination with the system-polyfill file.

`Potentially unhandled rejection [3] (SystemJS) Syntax error
SyntaxError: Syntax error`

Added the file (system-polyfill.js) to WeTransfer. Maybe you can check it with the combination.

http://we.tl/t-qlrBjCZ22R
